- docs/content/widgets/ColorFields.js
- docs/content/widgets/ColorPickers.js
- docs/content/widgets/configs/ColorField.js
- docs/content/widgets/configs/ColorPicker.js
ColorPickers and ColorFields edited
> Color field edit

- docs/content/charts/NumericAxis.js
- docs/content/widgets/Checkboxes.js
- docs/content/widgets/DateFields.js
- docs/content/widgets/Grids.js
- docs/content/widgets/Links.js
- docs/content/widgets/NumberFields.js
- docs/content/widgets/Radios.js
- docs/content/widgets/TextAreas.js
- docs/content/widgets/TextFields.js
This merge will do following:
* Intro text taken out the codeSplit in NumericAxis, CheckBoxes, DateFields, Grids, Links, NumberFields, Radios, TextAreas and TextFields.
> Intro text edit

- docs/content/widgets/ColorFields.js
- docs/content/widgets/ColorPickers.js
- docs/content/widgets/configs/ColorField.js
- packages/cx-core/src/ui/form/ColorPicker.js
This pull includes:
* ColorField and ColorPicker code alignment,
* ColorField config update on the value and format property,
* In ColorField, second field added with hsla representation.
> ColorField and ColorPicker edit

- packages/cx-core/src/ui/grid/Pagination.js
This pull request includes:
* Pagination tabbing edit (skips page numbers that are not selected)
> Pagination edit

- docs/content/widgets/TextFields.js
- docs/content/widgets/configs/TextField.js
- packages/cx-core/src/ui/form/TextField.js
* TextField minValue and maxValue property added
* TextField minValue and maxValue property added in config\TextField
> TextField minValue and maxValue property added

- packages/cx-core/src/ui/form/Calendar.js
Implement hide calendar cursor on mouse leave when the component has no focus.
> Calendar bug fix

- packages/cx/src/widgets/form/Radio.scss
Radio text didn't change color in disabled mod.
> Fix issue with disabled radio text

- packages/cx/locale/es-es.js
- packages/cx/locale/sr-latn-ba.js
I've added a new file for Spanish localization (es-es.js) and made some changes to sr-latn-ba.js. Someone who actually knows Spanish should check the file...
> Localization files

- benchmark/data/expressions.js
- benchmark/grid/100-rows.js
- benchmark/index.js
- benchmark/index.scss
- packages/cx/src/data/Expression.js
- packages/cx/src/data/Expression.spec.js
- packages/cx/src/data/computable.js
Allows expression to be written like this.
```
<div visible:expr={get=>!get('x.y')} />
```
> Add get based expressions

- docs/content/widgets/configs/Grid.js
Update Grid config table to include onRowDoubleClick property
> Document onRowDoubleClick Grid property

- docs/content/concepts/Localization.js
- packages/cx/locale/de-de.js
- packages/cx/locale/en-us.js
- packages/cx/locale/es-es.js
- packages/cx/locale/fr-fr.js
- packages/cx/locale/nl-nl.js
- packages/cx/locale/sr-latn-ba.js
- packages/cx/src/widgets/overlay/MsgBox.js
Added support for Dutch. Message box buttons translated.
> Msgbox translations

- packages/cx-theme-material-dark/src/variables.scss
- packages/cx-theme-material-dark/src/widgets.scss
Minor fixes based on Ogi's suggestions:
1. Grid header is darker and text is uppercase
2. Drag and clone background color changed
3. Border on input fields are lighter
4. Added border on checkbox
> Fixes on material-dark theme

- packages/cx/package.json
- packages/cx/src/charts/Marker.js
- packages/cx/src/ui/Cx.js
- packages/cx/src/widgets/HtmlElement.js
- packages/cx/src/widgets/List.js
- packages/cx/src/widgets/form/Calendar.js
- packages/cx/src/widgets/form/Checkbox.js
- packages/cx/src/widgets/form/ColorField.js
- packages/cx/src/widgets/form/ColorPicker.js
- packages/cx/src/widgets/form/DateTimeField.js
- packages/cx/src/widgets/form/DateTimePicker.js
- packages/cx/src/widgets/form/LookupField.js
- packages/cx/src/widgets/form/MonthField.js
- packages/cx/src/widgets/form/MonthPicker.js
- packages/cx/src/widgets/form/NumberField.js
- packages/cx/src/widgets/form/Radio.js
- packages/cx/src/widgets/form/Select.js
- packages/cx/src/widgets/form/Slider.js
- packages/cx/src/widgets/form/TextArea.js
- packages/cx/src/widgets/form/TextField.js
- packages/cx/src/widgets/form/Wheel.js
- packages/cx/src/widgets/grid/Grid.js
> Replace componentWillReceiveProps with UNSAFE_componentWillReceiveProps

- docs/app/index.scss
https://github.com/codaxy/cxjs/issues/687
> Change overflow in Cxjs docs content #687

- docs/content/widgets/configs/Grid.js
> Document row property for grids

- docs/content/widgets/configs/GridColumn.js
https://github.com/codaxy/cxjs/issues/633
> Document the caption grid column property

- docs/content/widgets/configs/LookupField.js
- packages/cx/src/widgets/form/LookupField.d.ts
- packages/cx/src/widgets/form/LookupField.js
Not sure if onItemClick method should be updated as well.
> Lookup submit on dropdown enter

- docs/content/widgets/DateTimeFields.js
> Added example, snippet, configuration, fixed fiddles

- docs/content/widgets/configs/UploadButton.js
- litmus/features/uploadButton/index.js
- litmus/index.js
- packages/cx/src/widgets/form/UploadButton.d.ts
- packages/cx/src/widgets/form/UploadButton.js
> Add accept attribute to filter file types in file expolorer #726

- docs/app/DocsNav.js
- docs/content/examples/form/CustomLookupBindings.js
- docs/content/examples/form/InfiniteLookupList.js
- docs/content/examples/form/index.js
- docs/content/examples/index.js
- docs/content/examples/lookup/index.js
- docs/content/widgets/LookupFields.js
- docs/content/widgets/configs/LookupField.js
- litmus/features/lookupfield/Infinite.js
- litmus/index.js
- litmus/webpack.config.js
- packages/cx/src/widgets/List.d.ts
- packages/cx/src/widgets/List.js
- packages/cx/src/widgets/form/LookupField.d.ts
- packages/cx/src/widgets/form/LookupField.js
> Add LookupField infinite mode

- docs/content/examples/form/InfiniteLookupList.js
- packages/cx/src/widgets/form/LookupField.js
Enable deleting all selected records in multiple Lookupfield (client request).
> Enable clearing all selected records in multiple LookupField

- docs/content/charts/MinMaxFinder.js
- docs/content/charts/SnapPointFinder.js
- docs/content/examples/charts/bar/ScrollableBars.js
- docs/content/examples/grid/FixedColumns.js
- docs/content/examples/grid/Grouping.js
- docs/content/widgets/Menus.js
- docs/content/widgets/ProgressBars.js
- docs/content/widgets/Resizers.js
- docs/content/widgets/Texts.js
Added fiddle and used tabs in the documentation.
> Fixed missing fiddles

- docs/content/widgets/Validators.js
https://github.com/codaxy/cxjs/issues/803
> Add missing fiddle on Validators

- docs/content/widgets/ContentResolvers.js
https://github.com/codaxy/cxjs/issues/798
> Add missing Fiddle on ContentResolver

- docs/content/widgets/NumberFields.js
Fixed documentation on issue #387
> Issue #387 fix

- docs/content/intro/Welcome.js
Fixed error regarding nesting div into p tag, on welcome page.
> Quick fix - Nesting div into p tag

- docs/content/widgets/configs/Window.js
Closable works, but not closeable. Description fix.
> Remove incorrect description from windows

- docs/content/widgets/FieldGroups.js
- docs/content/widgets/configs/Checkbox.js
- packages/cx/src/widgets/form/Checkbox.d.ts
- packages/cx/src/widgets/form/Checkbox.js
Not sure whether renderValue is semantically correct method to render the viewText, but it seemed neat since we didn't have to make a lot of changes. :)
> show viewText if set, for checkbox in view mode

- docs/content/concepts/ImmerJsIntegration.js
- docs/content/concepts/TypedModels.js
Fix link from Typed Models to Immer, and small typo.
> Small documentation fixes

- packages/cx/src/ui/Repeater.d.ts
> TS > Repeater: keyField is not mandatory

- litmus/bugs/LookupFieldListItemFocus.js
- litmus/index.js
- packages/cx/src/widgets/List.js
> fix issue with lookup field first option getting focus even when disabled

- packages/cx/src/widgets/nav/MenuItem.d.ts
> add MenuItem confirm prop and remove extraneous onClick prop

- packages/cx/src/widgets/form/NumberField.d.ts
> Optional parameters fix 

- packages/cx/src/ui/Repeater.d.ts
Typed as any, like in the Grid.
> Missind prop dataAdapter

- packages/cx/src/widgets/grid/Grid.d.ts
- packages/cx/src/widgets/grid/Grid.js
- packages/cx/src/widgets/grid/GridRow.js
provide an option to mark grid rows as non draggable
> add grid onCreateIsRecordDraggable callback

- packages/cx/src/widgets/form/ColorField.js
Co-authored-by: Ognjen Stefanovic <ognjen.stefanovic@codaxy.com>
> Dismiss after scroll

- packages/cx/src/charts/helpers/MinMaxFinder.d.ts
- packages/cx/src/charts/helpers/MinMaxFinder.js
- packages/cx/src/charts/helpers/PointReducer.d.ts
Rename MinMaxReducer to MinMaxFinder.
Add export declaration to PointReducerProps class.
> Rename MinMaxReducer to MinMaxFinder.

- packages/cx/src/widgets/form/LookupField.js
> fix lookup field active option search

- packages/cx/src/charts/PieLabelsContainer.d.ts
- packages/cx/src/widgets/drag-drop/DragSource.d.ts
Fix TS type definitions for PieLabelsContainer and DragSource.
> Improve TS type definitions

- docs/content/widgets/Grids.js
- packages/cx/src/widgets/grid/Grid.js
> display column footer when neither grouping nor aggregates nor fixedFooter are used

- docs/content/charts/Columns.js
- docs/content/charts/PieLabels.js
- fiddle/app/components/OpenDialog.js
- fiddle/app/routes/login/PickAuthProviderPage.js
We missed it somehow in a few places
> Replace :bind with -bind

- docs/content/concepts/DataViews.js
- docs/content/concepts/Formatting.js
Expanded formatting documentation by adding fields for user interaction. Adjusted the order of sections.
> Expanded formatting documentation

- docs/content/concepts/Formatting.js
Set default values for number and date fields.
> Set default values

- docs/content/examples/grid/ColumnResizing.js
- docs/content/widgets/configs/Grid.js
- packages/cx/src/widgets/grid/Grid.d.ts
- packages/cx/src/widgets/grid/Grid.js
update 'Column Resizing' example to reflect onRef implementation
> add grid onRef callback

- fiddle/app/routes/default/Header.js
Fixed another typo where two words were concatenated.
> Fix a typo

- docs/content/charts/BarGraphs.js
- docs/content/charts/Bars.js
- docs/content/charts/ColorMap.js
- docs/content/charts/ColumnGraphs.js
- docs/content/charts/Columns.js
- docs/content/charts/Legend.js
- docs/content/charts/LineGraphs.js
- docs/content/charts/Markers.js
- docs/content/charts/PieCharts.js
- docs/content/charts/PieLabels.js
- docs/content/charts/Ranges.js
- docs/content/charts/TimeAxis.js
- docs/content/charts/configs/ColumnBarGraphBase.js
- docs/content/concepts/Localization.js
- docs/content/concepts/Selections.js
- docs/content/widgets/Tooltips.js
Updated documentation by:
- Using `onInit()` instead of `init()` and removing `super.init()` from several files
- Localization:
- Changing order of the fields so that calendar is right below the date field
- Set date field to _read-only_ to prevent displaying another calendar on top of the existing one
- Set button's _pressed_ property
- Fix typos
> Update localization documentation

- docs/content/concepts/Localization.js
> Document new culture methods

- docs/app/DocsNav.js
- docs/content/concepts/DragAndDrop.js
- docs/content/examples/grid/RowDragAndDrop.js
- docs/content/examples/grid/RowDragAndDrop.scss
- docs/content/examples/grid/RowReordering.js
- docs/content/examples/grid/index.js
- docs/content/widgets/Grids.js
- docs/content/widgets/configs/GridDragAndDrop.js
- packages/cx/src/widgets/grid/Grid.d.ts
- Create examples of drag & drop within a Grid
- Create specific page for Drag and Drop (variations of drag and drop within a Grid)
- Insert link to the page into Drag & Drop and Grids pages
- Add drag & drop configuration to Grid
> Create page for Row Drag & Drop

- docs/content/concepts/Store.js
- packages/cx/src/data/ops/updateTree.js
- packages/cx/src/data/ops/updateTree.spec.js
- Fix bug where nothing was set in the store from Store.js controller due to using `init` on `$page`
- Add `updateTree` explanation and example
> Update Store docs

- docs/content/concepts/Formatting.js
- docs/content/intro/StepByStep.js
- Use `CodeSnippet` for `.json`
- Update usage of `Tab`s
> Refresh Step-by-step docs

- docs/content/concepts/Formatting.js
> Add usage of fmt to the example

- docs/content/concepts/Formatting.js
> Document new flags

- docs/content/concepts/Charts.js
- docs/content/concepts/DataBinding.js
- docs/content/concepts/InnerLayouts.js
- docs/content/concepts/Widgets.js
- Use `-bind`/`-expr`/`-tpl` suffixes instead of `:bind`/`:expr`/`:tpl`
- Remove dead code
- Fix code snippet indents
> Small clean up

- docs/content/widgets/DateTimeFields.js
- docs/content/widgets/configs/DateField.js
> Document onParseInput

- docs/content/concepts/Formatting.js
- docs/content/concepts/configs/DataProxy.js
- docs/content/concepts/configs/Formatting.js
- Move accounting flag under currency formatting
- Add an example for accounting format
- Create a separate config file
> Update number and currency formatting flags

- docs/app/DocsNav.js
- docs/content/concepts/KeyboardShortcuts.js
- docs/content/concepts/index.js
- packages/cx/src/ui/keyboardShortcuts.js
- Document `registerKeyboardShortcut`
- Add an example and a fiddle link
Closes #1050
> Document registerKeyboardShortcut

- packages/cx/src/widgets/grid/Grid.d.ts
This prop is documented, but it's missing from the props in TS. 
This is throwing an error in projects.
> Update Grid.d.ts interface and add onRowContextMenu callback

- packages/cx/src/widgets/form/index.js
Found by `swc_transform_cx_jsx`
> Add missing Label export

- docs/app/DocsNav.js
- docs/content/widgets/ValidationGroups.js
- docs/content/widgets/Validators.js
- docs/content/widgets/Validators.scss
- docs/content/widgets/configs/ValidationGroup.js
- docs/content/widgets/configs/Validator.js
> Document Validator & ValidationError

- docs/content/concepts/Selections.js
- packages/cx/src/ui/selection/KeySelection.d.ts
- packages/cx/src/ui/selection/PropertySelection.d.ts
- packages/cx/src/ui/selection/PropertySelection.js
- packages/cx/src/ui/selection/Selection.d.ts
> Document SimpleSelection

- packages/cx/src/widgets/grid/Grid.js
> Render headers in a single tbody element

- packages/cx/src/charts/Swimlanes.d.ts
- packages/cx/src/charts/Swimlanes.js
Prevent user to pass negative step value
Fix types
> Prevent user to pass negative step value

- packages/cx/src/charts/RangeMarker.d.ts
- packages/cx/src/charts/RangeMarker.js
Fix VDOM for range markers
Fix typo
> VDOM range markers fix

- litmus/index.js
- packages/cx/src/widgets/grid/Grid.js
> fix grid rendering when column caption is defined via items only

- docs/app/DocsNav.js
- docs/content/charts/Swimlane.js
- docs/content/charts/configs/Swimlane.js
- docs/content/charts/index.js
- packages/cx/src/charts/Swimlane.d.ts
- packages/cx/src/charts/Swimlane.js
- packages/cx/src/charts/Swimlane.scss
- packages/cx/src/charts/index.d.ts
- packages/cx/src/charts/index.js
- packages/cx/src/charts/index.scss
> Swimlane component

- docs/content/widgets/Grids.js
- docs/content/widgets/configs/GridColumn.js
- packages/cx/src/widgets/grid/Grid.d.ts
- packages/cx/src/widgets/grid/Grid.js
> add column primarySortDirection prop

- packages/cx/src/data/ArrayElementView.js
- packages/cx/src/data/ArrayElementView.spec.js
- packages/cx/src/data/AugmentedViewBase.js
- packages/cx/src/ui/DataProxy.spec.js
- ...
- Properly support nested aliases
> Support for nested store aliases

- litmus/bugs/PropertySelectionWithAccessorChain.tsx
- litmus/index.js
- packages/cx/src/ui/selection/PropertySelection.js
Fix the issue with property selection causing an error when grid records are accessor chain.
> Property Selection & Accessor chain

- packages/cx/src/ui/layout/ContentPlaceholder.d.ts
- packages/cx/src/ui/layout/ContentPlaceholder.js
- packages/cx/src/ui/layout/ContentPlaceholder.spec.js
- ...
- Allow multiple entries in content placeholders
> Allow multiple elements in content placeholders

- litmus/bugs/HighlightedTextSearchBug.js
- litmus/index.js
- packages/cx/src/util/getSearchQueryPredicate.js
> Add HighlightedTextSearchBug component and update

- packages/cx/src/data/Expression.js
- packages/cx/src/data/Expression.spec.js
- **...**
- **Expression parsing fixes**
> String templates in subexpressions

- litmus/index.js
- packages/cx/src/widgets/grid/Grid.js
> fix rhs resizing of the last fixed column in the Grid

- litmus/features/typescript/AccessorChainMethods.tsx
- litmus/index.js
- packages/cx/src/data/View.d.ts
* add litmus showcasing store methods type inference
> * enhance ViewMethods type definitions

- .vscode/settings.json
- packages/cx/package.json
- packages/cx/src/data/AugmentedViewBase.js
- packages/cx/src/data/ExposedRecordView.js
- packages/cx/src/data/ExposedValueView.js
- packages/cx/src/ui/Container.js
- packages/cx/src/ui/Cx.js
- packages/cx/src/ui/DataProxy.js
- packages/cx/src/ui/DetachedScope.js
- packages/cx/src/ui/Instance.d.ts
- packages/cx/src/ui/Instance.js
- packages/cx/src/ui/IsolatedScope.js
- packages/cx/src/ui/Repeater.js
- packages/cx/src/ui/Rescope.js
- packages/cx/src/ui/Restate.js
- packages/cx/src/ui/Widget.js
- packages/cx/src/ui/adapter/ArrayAdapter.js
- packages/cx/src/ui/adapter/TreeAdapter.js
- packages/cx/src/ui/createFunctionalComponent.js
- packages/cx/src/ui/layout/exploreChildren.d.ts
- packages/cx/src/ui/layout/exploreChildren.js
- packages/cx/src/widgets/List.js
- packages/cx/src/widgets/Sandbox.js
- packages/cx/src/widgets/grid/Grid.js
- packages/cx/src/widgets/nav/Route.js
- packages/cx/src/widgets/overlay/Tooltip.js
- **Use parent stores to prevent store change floods**
- **...**
- **...**
- **...**
- **Performance optimization and correctnes**
- **New cx@beta release**
- **...**
- **Test if data can be uses as a weak map key**
- **New cx beta**
> Optimize store changes in widget trees
