codaxy/cxjs

docs/content/concepts/Css.js
Import paths for themes should be OK now.
Important to note: 
* when using the neutral theme, index.scss and variables.scss are imported from the cx-core/src folder whose webpack alias is 'cx', so the correct import path is ~cx/variables and ~cx/index
* on the other hand, webpack aliases for theme packages do not include the 'src' folder, so it needs to be appended to the import path, e.g. @import '~cx-theme-frost/src/variables'
=> Fix theme paths

packages/cx-core/src/variables.scss
When not focused, a background color of selected list item was gray. Now it's light blue in neutral theme.
=> Selected list item background color changed 

packages/cx/src/widgets/form/TextField.d.ts
Hello there! We've been looking for an alternative to ExtJS for a new project and have stumbled upon Cx, which looks like a wonderful product at a first glance. We're currently evaluating Cx with TS. I'm going to send a few PRs with issues I've encountered so far.
=> Modify TextField.icon type definition to allow binding

packages/cx-cli/tpl/app/layout/index.js, packages/cx-cli/tpl/app/routes/dashboard/index.js, packages/cx-cli/tpl/app/routes/index.js, packages/cx-cli/tpl/app/routes/users/Editor.js, packages/cx-cli/tpl/app/routes/users/List.js, packages/cx-cli/tpl/app/routes/users/index.js
I performed a test with `yarn create cx-app` and manual syntax replacement, and the bindings were working correctly (there is already a `"babel-preset-env": "^1.6.1"` devDependency inside `tpl/package.json` file) so it should be safe to merge this to the master and republish the cx-cli npm package.
=> Replace :bind with -bind syntax in cx-cli scaffold template

packages/cx/src/data/View.js, packages/cx/src/ui/Component.d.ts, packages/cx/src/ui/Controller.js, packages/cx/src/ui/Controller.spec.js
This PR is introducing changes that simplify controller creation.
**1. Simpler controller definition**
```js
export default {
onInit() {
// ...
}
}
```
Note that it is not mandatory to use a class which extends the `Controller` base. One `import` statement less.
**2. Functional controllers**
```js
export default ({ store}) => ({
onInit() {
let user = store.get("user")
}
});
```
The main benefit is that `this` is not required for accessing the store in the controller. Knowing `this` upfront opens more possibilites.
*2.1. Declaration of store references*
This is similar to the concept explained in #347.
```js
export default ({ store}) => {   
const userRef = store.ref("user");
const statusRef = store.ref("status");
return {
onInit() {    
let user = userRef.value(); //store.get("user"); …
```
=> Functional controllers

docs/content/widgets/configs/TreeNode.js, packages/cx/src/widgets/grid/TreeNode.d.ts, packages/cx/src/widgets/grid/TreeNode.js
Add hideArrow property to TreeNode widget to be able to hide arrow if folder node has no children.
=> add TreeNode hideArrow property

packages/cx/src/widgets/grid/Grid.js
fix grid methods for getting scroll parents in case when grid is not marked as scrollable
=> fix grid drag & drop

docs/content/widgets/LookupFields.js, packages/cx/src/widgets/form/LookupField.js
The condition `!this.state.dropdownOpen` on line 829 was added to avoid showing `loading...` text on every keystroke, which caused a bug where `loading...` is not displayed at all after typing a query. Consequently LookupField appeared as if not working, with results popping up after a while. The issue was especially noticable on queris that took longer to execute. 
I removed that condition since we would normally use query delay to handle the issue it was meant to fix, and in all other cases when onQuery is fetching remote data, we actually want the loading indicator to show.
I also modified the example to be more realistic (it is common to define `minQueryLength` when not using `fetchAll`).
=> Lookup field bug

litmus/bugs/submitOnEnter.js, litmus/index.js, packages/cx/src/widgets/form/LookupField.js
Currently LookupField fires onSubmit only if dropdown contains a search field (input) which has focus and fires the onSubmit event on Enter. 
If we don't show the dropdown, the event is never fired, so there is nothing to propagate. 
One possible solution, as suggested below, is to simply check if one of the parent components contains the onSubmit method and to call it directly.
=> submitOnEnter bug litmus and a possible solution

docs/content/intro/GettingStarted.js
There was an English mistake in the 'Advanced Concepts' part.
=> Minor fix in GettingStarted.js

packages/cx/src/widgets/form/Calendar.js, packages/cx/src/widgets/form/DateTimeField.js, packages/cx/src/widgets/form/LookupField.js
Seems like the issue wasn't with the onClick event. Menu was getting dismissed because input wouldn't get focus after dropdown closing.
=> keep focus on input element after dropdown close

packages/cx/src/widgets/form/LookupField.js
I've removed the logic from the componentDidMount method, not sure if it's correct but it seemed redundant.
=> open lookup on focus if autoOpen flag is set

litmus/bugs/AsyncValidator.js, litmus/index.js, packages/cx/src/widgets/form/Field.js
See https://fiddle.cxjs.io/?f=Ngxbn2M6# for details. This tiny PR
would fix issues 2 and 3. It's not clear why it was undesirable to invoke 
`onValidate` when the field is empty in the first place, but I'm sure
there's a good reason for it. So, I left the behavior intact for 
the synchronous validators (which is 99% of the cases), while
giving a chance to the fields with asynchronous validators
to revalidate (and, possibly, clear out stale errors if that is the 
requirement) when cleared.
Issue 1 is not that easy to fix, as `prevouslyValidated` and
`lastValidatedValue` are "cached". I don't see a chance to
clear them easily, since the revalidation in that case should be
triggered by an unrelated store variable change.
=> Field.js: Improve async onValidate behavior

packages/cx/package.json, packages/cx/src/widgets/grid/Grid.js, packages/cx/src/widgets/grid/Grid.scss
Render hidden footers for buffered grids for proper column sizing.
=> Show fixed footers even if grid is not scrollable

docs/components/CodeSnippet.scss
When scrolling, fiddle button would go over navbar.
=> Fix: Remove z-index form fiddle button

packages/cx/src/widgets/nav/Link.d.ts, packages/cx/src/widgets/nav/LinkButton.d.ts
Changing the base class of the Link component. Some properties that are used have the TS definition is missing because there is a wrong base class in TS component.
=> Change base class of Link compontnt

packages/cx/src/ui/layout/Content.d.ts
Please check if the comments are acceptable. In the `onInit` function, if both `name` and `for` properties are defined, `for` will be used, so I tried to clarify that.
=> TS > Missing Props: Content

packages/cx/src/data/View.d.ts
The problem was if the `set<V>(path: AccessorChain<V>, value: V)` signature is not matched, the `set(path: Record, value: Record)` will match even if the path is of `AccessorChain` type
I could not find any other solution except removing `set(Record, Record)` 
I do not know the impact of this change.
=> Fix view methods precedence

docs/content/widgets/configs/Overlay.js
I didn't add specific description for zIndex and resizeWidth properties
=> add missing configuration properties to Overlay component documentation

litmus/features/slider/SliderPreventDefault.js, litmus/index.js, packages/cx/src/widgets/form/Slider.js
`Wheel` is a passive event listener, which means that it will never call `preventDefault`, as per [documentation](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener).
=> Remove preventDefault from onWheel listner in Slider

docs/app/DocsNav.js, docs/content/examples/grid/DynamicColumns.js, docs/content/examples/grid/index.js, docs/content/widgets/Grids.js
We've had a complex use-case with dynamically configured visible columns and row expanding grid, and figured out that we are lacking documentation for such a use case, so I thought it would be nice to have a dedicated example for that. :)
=> add dynamic columns grid example showcasing onGetColumns callback

packages/cx/src/widgets/overlay/Overlay.js
This PR is related to bug that is reported on Lorino: [SL-619](https://yt.codaxy.com/issue/SL-619/Feed-Modals-preventing-page-zoom-in)
I was looking at handleKeyDown() in Overlay.js but didn't find anything unusual, then I searched for handling of wheel events.
I just added ctrlKey where check for shiftKey was to allow default behavior of wheel event within shadowEl **while Ctrl is pressed**.
I haven't noticed any unusual behaviour after the addition.
=> allow ctrl+wheel zoom while modals are opened

packages/cx/src/ui/Repeater.d.ts, packages/cx/src/widgets/List.d.ts, packages/cx/src/widgets/grid/Grid.d.ts
Other types/interfaces to consider within Grid component:
* `MappedGridRecord`: it has a data property of type `Record`, however, I wasn't sure whether it's a record from the Grid records property, or some wrapper around it.
* `GridDragEvent`: `recordBefore` and `recordAfter` are of the `MappedGridRecord` type.
* `GridRowDragEvent`: similar like the previous one, `record` is of type `MappedGridRecord`.
* `GridCellBeforeEditInfo`: has `data` property which somewhat suggests connection with the records.
* `onBeforeCellEdit` and `onCellEdited` callbacks receive `record: DataAdapterRecord` as a second argument. Could this also be a Generic - `DataAdapterRecord<T>`, since this type has a `data` property of type any.
=> support providing/inferring records type for repeater, list and grid

packages/cx-cli/index.js
Fixed an issue with adding a new route. A bug was introduced recently where adding a route worked only in this way:
- `cx add, sign-in ignored` (with a comma) - This would add a route with name `sign-in`.
instead of:
- `cx add route sign-in`
=> Fix cx-cli parsing

docs/app/DocsNav.js, docs/content/examples/grid/TreeGrid.js, docs/content/widgets/Grids.js, docs/content/widgets/TreeGrid.js, docs/content/widgets/configs/Grid.js, docs/content/widgets/configs/TreeNode.js
- Add `dataAdapter` property to Grid documentation.
- Update docs navigation to include `examples/grid/tree-grid`.
- Update `examples/grid/tree-grid` page:
- Split controller and widgets code into separate tabs.
- Fix formatting.
=> Document dataAdapter property

packages/cx/src/widgets/form/ColorField.js, packages/cx/src/widgets/form/DateTimeField.js, packages/cx/src/widgets/form/MonthField.js, packages/cx/src/widgets/form/NumberField.js, packages/cx/src/widgets/form/TextArea.js, packages/cx/src/widgets/form/TextField.js
The `blur` event is not sent before unmounting, so we have to do it manually.
=> Apply changes before unmounting focused fields

docs/app/DocsNav.js, docs/content/concepts/CxComponent.js, docs/content/concepts/configs/CxComponent.js, docs/content/concepts/index.js, packages/cx/src/ui/Cx.d.ts, packages/cx/src/ui/app/startAppLoop.js
=> Document Cx component and injecting Cx widgets into React

packages/cx/src/widgets/form/LabeledContainer.d.ts, packages/cx/src/widgets/form/ValidationGroup.d.ts
* LabeledContainer disabled prop shouldn't be inherited from FieldGroup
=> * ValidationGroup asterisk prop should be a prop

docs/content/widgets/configs/LinkButton.js, packages/cx/src/widgets/nav/LinkButton.js
Useful e.g. for file download link buttons.
=> Add support for `target` property

litmus/features/calendar/year-selection.js, litmus/index.js, packages/cx/src/widgets/form/Calendar.js, packages/cx/src/widgets/form/Calendar.scss
When selecting something like a date of birth, we need to scroll through the years a lot. 
Now, you can click on the year, select a proper year, and then select the date.
=> Add support for year selector in calendar

litmus/bugs/grid-clearable-sort.js, litmus/index.js, packages/cx/src/widgets/grid/Grid.js
When we add sortDirection and sortField bindings to the Grid, prepareData always initializes the sorters array, since it has sortField. This causes issues, since the only check when applying mods is to see if there are sorters, or if the name is defined (it always is).
=> Fix issue with clearable sort

litmus/features/month-field/withMonthPickerOptions.js, litmus/index.js, packages/cx/src/widgets/form/MonthField.d.ts, packages/cx/src/widgets/form/MonthField.js, packages/cx/src/widgets/form/MonthPicker.js
Allow passing additional config options to the MonthPicker rendered within a dropdown of MonthField component.
=> Add monthPickerOptions to the MonthField component
